version "3.8"
services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./blog:/app
    ports:
      - "8000:8000"
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=docker_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123